// <auto-generated />
namespace LinkShortener.Db.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_t_UserBlockedStatuses : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_t_UserBlockedStatuses));
        
        string IMigrationMetadata.Id
        {
            get { return "201902251650583_add_t_UserBlockedStatuses"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
